module.exports = {
    1: [["upperBodyGroup", "rotation", "0.05"], ["upperBodyGroup", "y", 2], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.03"], ["leftHandGroup", "rotation", "0.09"],
        ["rightHandGroup", "rotation", "-0.04"], ["leftHandBottom", "rotation", "-0.04"], ["rightHandBottom", "rotation", "-0.03"], ["leftFootGroup", "rotation", "-0.1"],
        ["rightFootGroup", "rotation", "0.13"], ["leftFootBottom", "rotation", "0.36"], ["rightFootBottom", "rotation", "0.23"]],
    2: [["upperBodyGroup", "rotation", "0.07"], ["upperBodyGroup", "y", 2], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.03"], ["leftHandGroup", "rotation", "0.12"],
        ["rightHandGroup", "rotation", "-0.12"], ["leftHandBottom", "rotation", "0.02"], ["rightHandBottom", "rotation", "-0.14"], ["leftFootGroup", "rotation", "-0.15"],
        ["rightFootGroup", "rotation", "0.03"], ["leftFootBottom", "rotation", "0.29"], ["rightFootBottom", "rotation", "0.97"]],
    3: [["upperBodyGroup", "rotation", "0.1"], ["upperBodyGroup", "y", 2], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.03"], ["leftHandGroup", "rotation", "0.39"],
        ["rightHandGroup", "rotation", "-0.25"], ["leftHandBottom", "rotation", "-0.1"], ["rightHandBottom", "rotation", "-0.29"], ["leftFootGroup", "rotation", "-0.33"],
        ["rightFootGroup", "rotation", "0.1"], ["leftFootBottom", "rotation", "0.2"], ["rightFootBottom", "rotation", "1.09"]],
    4: [["upperBodyGroup", "rotation", "0.14"], ["upperBodyGroup", "y", -5], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.03"], ["leftHandGroup", "rotation", "0.51"],
        ["rightHandGroup", "rotation", "-0.4"], ["leftHandBottom", "rotation", "-0.03"], ["rightHandBottom", "rotation", "-0.47"], ["leftFootGroup", "rotation", "-0.49"],
        ["rightFootGroup", "rotation", "0.32"], ["leftFootBottom", "rotation", "0"], ["rightFootBottom", "rotation", "1.42"]],
    5: [["upperBodyGroup", "rotation", "0.14"], ["upperBodyGroup", "y", -5], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.03"], ["leftHandGroup", "rotation", "0.51"],
        ["rightHandGroup", "rotation", "-0.4"], ["leftHandBottom", "rotation", "-0.03"], ["rightHandBottom", "rotation", "-0.47"], ["leftFootGroup", "rotation", "-0.49"],
        ["rightFootGroup", "rotation", "0.32"], ["leftFootBottom", "rotation", "0"], ["rightFootBottom", "rotation", "1.42"]],
    6: [["upperBodyGroup", "rotation", "0.1"], ["upperBodyGroup", "y", 2], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.03"], ["leftHandGroup", "rotation", "0.39"],
        ["rightHandGroup", "rotation", "-0.25"], ["leftHandBottom", "rotation", "-0.1"], ["rightHandBottom", "rotation", "-0.29"], ["leftFootGroup", "rotation", "-0.33"],
        ["rightFootGroup", "rotation", "0.1"], ["leftFootBottom", "rotation", "0.2"], ["rightFootBottom", "rotation", "1.09"]],
    7: [["upperBodyGroup", "rotation", "0.07"], ["upperBodyGroup", "y", 2], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.03"], ["leftHandGroup", "rotation", "0.12"],
        ["rightHandGroup", "rotation", "-0.12"], ["leftHandBottom", "rotation", "0.02"], ["rightHandBottom", "rotation", "-0.14"], ["leftFootGroup", "rotation", "-0.15"],
        ["rightFootGroup", "rotation", "0.03"], ["leftFootBottom", "rotation", "0.29"], ["rightFootBottom", "rotation", "0.97"]],
    8: [["upperBodyGroup", "rotation", "0.05"], ["upperBodyGroup", "y", 2], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.03"], ["leftHandGroup", "rotation", "-0.09"],
        ["rightHandGroup", "rotation", "0.04"], ["leftHandBottom", "rotation", "-0.04"], ["rightHandBottom", "rotation", "-0.03"], ["leftFootGroup", "rotation", "-0.1"],
        ["rightFootGroup", "rotation", "0.13"], ["leftFootBottom", "rotation", "0.36"], ["rightFootBottom", "rotation", "0.23"]]
};