module.exports = {
    1: [["upperBodyGroup", "rotation", "0.08"], ["upperBodyGroup", "y", 2], ["lowerBodyGroup", "rotation", "-0.19"], ["headGroup", "rotation", "-0.09"], ["leftHandGroup", "rotation", "-0.19"],
        ["rightHandGroup", "rotation", "0.05"], ["leftHandBottom", "rotation", "-0.08"], ["rightHandBottom", "rotation", "-0.25"], ["rightFootGroup", "rotation", "-0.02"],
        ["leftFootBottom", "rotation", "0.31"], ["rightFootBottom", "rotation", "0.12"]],
    2: [["upperBodyGroup", "rotation", "0.22"], ["upperBodyGroup", "y", 12], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.09"], ["leftHandGroup", "rotation", "-0.37"],
        ["rightHandGroup", "rotation", "0.16"], ["leftHandBottom", "rotation", "-0.47"], ["rightHandBottom", "rotation", "0.18"], ["leftFootGroup", "rotation", "0.01"],
        ["rightFootGroup", "rotation", "-0.19"], ["leftFootBottom", "rotation", "0.34"], ["rightFootBottom", "rotation", "0.28"]],
    3: [["upperBodyGroup", "rotation", "0.22"], ["upperBodyGroup", "y", 7], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.09"], ["leftHandGroup", "rotation", "-0.37"],
        ["rightHandGroup", "rotation", "0.16"], ["leftHandBottom", "rotation", "-0.47"], ["rightHandBottom", "rotation", "0.18"], ["leftFootGroup", "rotation", "0.01"],
        ["rightFootGroup", "rotation", "-0.19"], ["leftFootBottom", "rotation", "0.34"], ["rightFootBottom", "rotation", "0.28"]],
    4: [["upperBodyGroup", "rotation", "0.22"], ["upperBodyGroup", "y", -8], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.09"], ["leftHandGroup", "rotation", "-0.37"],
        ["rightHandGroup", "rotation", "0.16"], ["leftHandBottom", "rotation", "-0.47"], ["rightHandBottom", "rotation", "0.18"], ["leftFootGroup", "rotation", "0.01"],
        ["rightFootGroup", "rotation", "-0.19"], ["leftFootBottom", "rotation", "0.34"], ["rightFootBottom", "rotation", "0.28"]],
    5: [["upperBodyGroup", "rotation", "0.3"], ["upperBodyGroup", "y", -8], ["lowerBodyGroup", "rotation", "0.09"], ["headGroup", "rotation", "-0.09"], ["leftHandGroup", "rotation", "-0.39"],
        ["rightHandGroup", "rotation", "0.53"], ["leftHandBottom", "rotation", "-0.45"], ["rightHandBottom", "rotation", "0.12"], ["leftFootGroup", "rotation", "-0.1"],
        ["rightFootGroup", "rotation", "-0.44"], ["leftFootBottom", "rotation", "0.82"], ["rightFootBottom", "rotation", "0.08"]],
    6: [["upperBodyGroup", "rotation", "0.3"], ["upperBodyGroup", "y", 7], ["lowerBodyGroup", "rotation", "0.09"], ["headGroup", "rotation", "-0.09"], ["leftHandGroup", "rotation", "-0.39"],
        ["rightHandGroup", "rotation", "0.53"], ["leftHandBottom", "rotation", "-0.45"], ["rightHandBottom", "rotation", "0.12"], ["leftFootGroup", "rotation", "-0.1"],
        ["rightFootGroup", "rotation", "-0.44"], ["leftFootBottom", "rotation", "0.82"], ["rightFootBottom", "rotation", "0.08"]],
    7: [["upperBodyGroup", "rotation", "0.22"], ["upperBodyGroup", "y", 12], ["lowerBodyGroup", "rotation", "-0.18"], ["headGroup", "rotation", "-0.09"], ["leftHandGroup", "rotation", "-0.37"],
        ["rightHandGroup", "rotation", "0.16"], ["leftHandBottom", "rotation", "-0.47"], ["rightHandBottom", "rotation", "0.18"], ["leftFootGroup", "rotation", "0.01"],
        ["rightFootGroup", "rotation", "-0.19"], ["leftFootBottom", "rotation", "0.34"], ["rightFootBottom", "rotation", "0.28"]],
    8: [["upperBodyGroup", "rotation", "0.08"], ["upperBodyGroup", "y", 2], ["lowerBodyGroup", "rotation", "-0.19"], ["headGroup", "rotation", "-0.09"], ["leftHandGroup", "rotation", "-0.19"],
        ["rightHandGroup", "rotation", "0.05"], ["leftHandBottom", "rotation", "-0.08"], ["rightHandBottom", "rotation", "-0.25"], ["rightFootGroup", "rotation", "-0.02"],
        ["leftFootBottom", "rotation", "0.31"], ["rightFootBottom", "rotation", "0.12"]]
};